name: SkillPulse Docker CI

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Backend Image
        run: |
          docker build -t $DOCKER_USERNAME/skillpulse-backend:${{ github.sha }} ./backend
          docker tag $DOCKER_USERNAME/skillpulse-backend:${{ github.sha }} $DOCKER_USERNAME/skillpulse-backend:latest

      - name: Push Backend Image
        run: |
          docker push $DOCKER_USERNAME/skillpulse-backend:${{ github.sha }}
          docker push $DOCKER_USERNAME/skillpulse-backend:latest

      - name: Build Frontend Image
        run: |
          docker build -t $DOCKER_USERNAME/skillpulse-frontend:${{ github.sha }} ./frontend
          docker tag $DOCKER_USERNAME/skillpulse-frontend:${{ github.sha }} $DOCKER_USERNAME/skillpulse-frontend:latest

      - name: Push Frontend Image
        run: |
          docker push $DOCKER_USERNAME/skillpulse-frontend:${{ github.sha }}
          docker push $DOCKER_USERNAME/skillpulse-frontend:latest
